# Generated by Django 5.2.4 on 2025-07-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
