# Generated by Django 5.2.4 on 2025-07-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_face_data',
        ),
    ]
