# Generated by Django 5.2.4 on 2025-07-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_has_face_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='face_folder',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
