# Generated by Django 5.2.4 on 2025-07-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.CharField(choices=[('in', 'Clock In'), ('out', 'Clock Out')], max_length=10),
        ),
    ]
